### ISSUE TITLE
word cloud visualization for the frequencies

### ISSUE THREAD

**Issue by yuvi1323** [yuvi1323/CSCE_5340_Group8_Open_Source_Project#2]
Estimation Time: Small (2 days)
Acceptance Criteria:
- A word cloud should visually represent word frequencies from the fetched news articles.
- Words should appear larger in the word cloud based on their frequency of occurrence.
- Users should have the option to exclude stopwords or filter by keyword length.
- The word cloud should automatically update when new data is fetched.
- The word cloud should be easy to interpret and customizable in terms of color, font, and layout.

- [x] #3

**Comment by SreeNandini-Peguda** [comment]
There were issues while working realted to API @Anirudh-Samala @yuvi1323

**Comment by yuvi1323** [comment]
I have updated @SreeNandini-Peguda  kindly recheck once

**Comment by SreeNandini-Peguda** [comment]
`wordcloud = WordCloud(width=800, height=800, background_color='white').generate(text)

# Display the generated wordcloud image
plt.figure(figsize=(8,8), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()`

**Comment by yuvi1323** [comment]
Thanks a lot for sharing @SreeNandini-Peguda it working
