### ISSUE TITLE
CSV-exporting-feature-to-save-news-articles

### ISSUE THREAD

**Issue by yuvi1323** [yuvi1323/CSCE_5340_Group8_Open_Source_Project#4]
Estimation Time: Large (5 days)
Acceptance Criteria:
- A CSV file should be generated based on the results fetched from news article queries.
- Each row in the CSV should represent a news article with columns for details such as title, publication date, author, source, and content.
- The user should be able to trigger the CSV export feature through a button or command in the user interface.
- The exported CSV should be compatible with Excel and other spreadsheet applications.
- Proper error handling and user feedback should be implemented if the export fails.

- [x] #3

**Comment by Anirudh-Samala** [comment]
I have made necessary changes to the code in order to run and generate the csv kindly check this one, thought there was an issue with API. I have handled it sucessfully
<img width="1172" alt="Screenshot 2024-10-20 at 11 31 16 AM" src="https://github.com/user-attachments/assets/314465a4-0eea-45a8-8221-6a9c737d91a8">

**Comment by Anirudh-Samala** [comment]
`import requests
import csv
import matplotlib.pyplot as plt
from wordcloud import WordCloud

# Ask for user input
query = input("Enter a keyword to search for: ")
num_articles = int(input("Enter the number of articles to retrieve: "))
filename = input("Enter a filename to save the CSV data: ")

# Replace YOUR_API_KEY with your actual NewsAPI key
url = f"https://newsapi.org/v2/everything?q={query}&pageSize=100&page=1&apiKey=8f89582e7ffc45f1b73faeca278f87e5"

articles = []

# Retrieve articles
num_pages = (num_articles - 1) // 100 + 1  # Calculate number of pages needed
for i in range(num_pages):
    response = requests.get(url.format(i + 1))
    if response.status_code == 200:
        data = response.json()
        articles += data["articles"]
    else:
        print("Error:", response.status_code)
        break

# Save data to a CSV file
with open(filename + ".csv", "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = ["title", "description"]
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for article in articles:
        writer.writerow({"title": article["title"], "description": article["description"]})

# Ask user if they want to see the word cloud visualization
show_wordcloud = input("Do you want to see the word cloud visualization? (yes/no): ").lower() == "yes"
`

**Comment by yuvi1323** [comment]
Thanks a lot Anirudh for sharing ill walk them through and ill let know the feedback

**Comment by yuvi1323** [comment]
Everything works well and I'm closing this issue
