### ISSUE TITLE
Implement advanced filtering options for NewsAPI integration

### ISSUE THREAD

**Issue by yuvi1323** [yuvi1323/CSCE_5340_Group8_Open_Source_Project#5]
Estimation Time: Medium (3 days)
Acceptance Criteria:

- Users should be able to filter news articles based on date range, author, and publication.
- The filters should work seamlessly with the existing NewsAPI integration.
- Results should reflect the applied filters and still export properly to CSV.
- Appropriate user feedback and error messages should appear if filters are invalid or no articles match the filters.

**Comment by yuvi1323** [comment]
Added detailed API documentation for Event Registry endpoints, including registration, rate limits, and error handling. Included Python and Node.js SDK examples.

**Comment by SreeNandini-Peguda** [comment]
Updated API documentation with query condition limits for free and paid users, added HTTP status codes, and provided YAML file for OpenAPI specification.

**Comment by yuvi1323** [comment]
Thanks for sharing inputs let me know in case of issues in future

**Comment by vamsi513** [comment]
Improved API documentation by adding rate-limiting details, usage of API keys, and sample responses for success and error scenarios.

**Comment by vamsi513** [comment]
There is a limitation with respet to number of pulls it can make like 1000 per day @yuvi1323 @Anirudh-Samala

**Comment by yuvi1323** [comment]
Yep I see that since we are using a free version the call per day are limited @vamsi513
